### ISSUE TITLE
Non-alphabetic characters in symbols and strings are not escaped properly

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/tree-sitter-supercollider#10]
![scrn-2021-04-17-14-07-00](https://user-images.githubusercontent.com/12082586/115112472-fc762500-9f85-11eb-8415-b02846f19edc.png)

`'hej.godaws'` is legit.

**Comment by madskjeldgaard** [comment]
I think this is  the same problem as https://github.com/madskjeldgaard/tree-sitter-supercollider/issues/4

**Comment by madskjeldgaard** [comment]
Or, rather has the same solution

**Comment by madskjeldgaard** [comment]
> I suspect we have to upgrade the `parser.c` file to cover this, eg. like Rust has solved it https://github.com/tree-sitter/tree-sitter-rust/blob/a360da0a29a19c281d08295a35ecd0544d2da211/src/scanner.c#L27

**Comment by madskjeldgaard** [comment]
This should be prioritized now I think as it is one of the last big bugs to squash. We probably need to take a look at the scanner.c file or look at some of the other tree-sitter grammars out there how they do this.

**Comment by madskjeldgaard** [comment]
This is now fixed
