### ISSUE TITLE
args: symbol trouble rouble double (tittles are hard)

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/tree-sitter-supercollider#11]
its me again :)
`args:` with a `'symbol'` are only colored correctly after symbol is longer than 0 . so to say..
makes sense via illustration, not words.
![scrn-2021-04-17-23-49-17](https://user-images.githubusercontent.com/12082586/115127545-9ca86a00-9fd7-11eb-9e85-de2ac391bcb6.png)
![scrn-2021-04-17-23-49-36](https://user-images.githubusercontent.com/12082586/115127548-9e722d80-9fd7-11eb-8486-2b0527489d43.png)

**Comment by madskjeldgaard** [comment]
This should be fixed now. It was a general problem with empty symbols not being recognized. Both `''` and `\` are now recognized as symbols
