### ISSUE TITLE
Implicit new marks class as "method_name"

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/tree-sitter-supercollider#16]
The outermost class implicit .new class method is not listed as a receiver ( so to say? hmm)  but instead just listed as a regular function call with a method name.

![scrn-2021-05-19-10-54-59](https://user-images.githubusercontent.com/12082586/118784472-55d8b900-b890-11eb-8d29-12a0a2c8e338.png)

**Comment by salkin-mada** [comment]
This is true for Ndef, SynthDef, Pdef etc. But not Ugens

**Comment by madskjeldgaard** [comment]
This has been fixed now
