### ISSUE TITLE
nvim-treesitter-refactor highlight_definitions fails

### ISSUE THREAD

**Issue by catniptwinz** [madskjeldgaard/tree-sitter-supercollider#21]
## Environment
- Arch Linux
- nvim 0.5.0 from pacman
- tree-sitter 0.20.0 from pacman
- nvim-treesitter b3aac12 on branch "master" (Current as of now.)
- nvim-treesitter-refactor 1a377fa on branch "master" (Current as of now.)
- tree-sitter-supercollider installed with `:TSInstall supercollider`
- `highlight_definitions` enabled in 'init.vim':
```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  refactor = {
    highlight_definitions = {
      enable = true
    }
  }
}
EOF
```

## Steps to Reproduce
- open 'example.scd' from this repo
- move cursor to line 2
- nvim throws:
```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua ...ist/start/nvim-treesitter/lua/nvim-treesitter/locals.lua:133: bad argument #1 to 'pairs' (table expected, got string)
```
- matches are not highlighted

## Expected Behavior
With highlight_definitions, matches for the identifier under the cursor are highlighted, as they are with other grammars.

## Further Info
- This issue also occurs if tree-sitter-supercollider is cloned/built/installed manually.
- Other grammars do not seem to have this issue (tested with treesitter-python-git from AUR).
- The same error message is also thrown by "smart_rename" and "navigation" in the refactor module; "highlight_current_scope" is working as expected, as is the highlight module.

**Comment by madskjeldgaard** [comment]
Hi ! Thanks so much for this bug report. Are you still having this issue?
I did a PR in nvim-treesitter that I think fixes this issue. It was merged not so long ago so if you update to the latest version and let me know if it is still an issue that would be cool! 

https://github.com/nvim-treesitter/nvim-treesitter/pull/1331

Best

**Comment by catniptwinz** [comment]
Thanks likewise for following up, and sorry I didn't get to this sooner; I'd disabled most of nvim-treesitter-refactor for sclang and had it on my to do list to try reenable it at some point and circle back to this issue since nvim-treesitter has been moving pretty quickly.

Anyway, it looks like your PR resolved the issue. I've updated nvim-treesitter and reenabled highlight_definitions, smart_rename, and navigation and so far everything is working as expected. I'd consider this issue closed now. Thanks again!
