### ISSUE TITLE
string highlighting

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/tree-sitter-supercollider#4]
some types of special strings is weirdly highlighted and indented wrong

```supercollider
var rules = [
    "W" -> "YF++ZF----XF[-YF----WF]++ ",
    "X" -> "+YF--ZF[---WF--XF]+",
    "Y" -> "-WF++XF[+++YF++ZF]-",
    "Z" -> "--YF++++WF[+ZF++++XF]--XF",
    "F" -> ""
];
```
![scrn-2021-02-12-23-50-34](https://user-images.githubusercontent.com/12082586/107830773-d917d980-6d8c-11eb-80cb-cbf3607614e0.png)

**Comment by madskjeldgaard** [comment]
I suspect we have to upgrade the `parser.c` file to cover this, eg. like Rust has solved it https://github.com/tree-sitter/tree-sitter-rust/blob/a360da0a29a19c281d08295a35ecd0544d2da211/src/scanner.c#L27

**Comment by madskjeldgaard** [comment]
Duplicate
