### ISSUE TITLE
Hexadecimal numbers not highlighting as one

### ISSUE THREAD

**Issue by madskjeldgaard** [madskjeldgaard/tree-sitter-supercollider#46]
Hexadecimal numbers do not highlight correctly as one number:
<img width="361" alt="Screenshot 2023-05-15 at 21 23 43" src="https://github.com/madskjeldgaard/tree-sitter-supercollider/assets/22474608/3b1f29bf-ae05-48d6-bc16-e02e74caac56">

**Comment by madskjeldgaard** [comment]
is this fixed now @xunil-cloud ?

**Comment by xunil-cloud** [comment]
Yes! :smiley_cat:

**Comment by madskjeldgaard** [comment]
> Yes! 😺

great, thanks!
