### ISSUE TITLE
arguments without commas 

### ISSUE THREAD

**Issue by cdbzb** [madskjeldgaard/tree-sitter-supercollider#6]
1) THANKS FOR THIS!

2) {| argOne argTwo|} currently doesn't highlight correctly

inserting comma or assignment works ie 

{|argOne, argTwo|} or {|argOne=0,argTwo|}

**Comment by madskjeldgaard** [comment]
I had no idea this was possible. Thanks for bringing up - will add it soon

**Comment by madskjeldgaard** [comment]
Thanks for the report. This is fixed now
