### ISSUE TITLE
array of Classes

### ISSUE THREAD

**Issue by cdbzb** [madskjeldgaard/tree-sitter-supercollider#7]
for example 

[SinOsc, Saw]  

doesn't highlight correctly!

cheers

**Comment by madskjeldgaard** [comment]
Thanks for the report. This is a bigger problem that should be addressed soon. Classnames should generally be treated as objects (which they aren't now unfortunately). Thanks for the report!

**Comment by madskjeldgaard** [comment]
This has been fixed now. Thanks for the report
