### ISSUE TITLE
Invalid character in group name

### ISSUE THREAD

**Issue by salkin-mada** [madskjeldgaard/tree-sitter-supercollider#9]
when using neovim-git compiled for ABI version 13
opening `.sc`and `.scd`files gives `:mess`
`W18: Invalid character in group name`

```
❯ nvim --version
NVIM v0.5.0-dev+1260-ga6504ec33
Build type: RelWithDebInfo
LuaJIT 2.0.5
...
❯ tree-sitter --version
tree-sitter 0.19
```
and `nvim-treesitter` plugin updated/synced just now.

**Comment by madskjeldgaard** [comment]
I don't think this is a problem with this grammar and I think it has been fixed in either treesitter or neovim or neovim-treesitter or wherever the error was. Reopen if it's still a problem (with this grammar)
